baseurl = "/"
languageCode = "en-us"
title = "Erco: Exabgp Routes Controller"
uglyURLs = true

[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
    # for more icons. The icons are represented by their corresponding
    # CSS class.

    # All projects of the portfolio are defined in their own files. 
    # You can find example projects at 'examples/projects'. Copy the 'projects' 
    # folder into the 'data' directory at the root of this Hugo site.
    # For more informtion take a look at the README.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Luc Didry"
    description = "Erco: Exabgp Routes Controller"


    # Navigation
    [params.navigation]
        brand = "Erco"

        [params.navigation.links]
            demo         = "Demo"
            more         = "About"
            installation = "Installation"
            contribute   = "Contribute"
            author       = "Author"


    [params.hero]
        # To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
        slogan     = "Erco: Exabgp Routes Controller"
        subtitle   = "Manage your routes announced by Exabgp easily"
        buttonText = "Find out more"


    [params.demo]
        headline    = "A powerful web interface to manage your announced routes"
        description = "<img src=\"img/erco-screenshot.png\" class=\"img-responsive\" alt=\"Erco screenshot\"><br>current version: v0.1 “Mortal Derby X”"
        buttonText  = "Try the demo"
        buttonLink  = "/demo/"

    [params.more]
        headline = "At your service"

        [[params.more.list]]
            icon = "fa-connectdevelop"
            title = "Free software — as in free speech"
            description = "Because freedom and openness matters."
            link = "/doc/license.html"

        [[params.more.list]]
            icon = "fa-book"
            title = "Documentation"
            description = "What you need to know to get ready to use Erco."
            link = "/doc/index.html"

        [[params.more.list]]
            icon = "fa-arrows-alt"
            title = "Restful API"
            description = "Connect your own interface to Erco."
            link = "/demo/api/index.html"

        [[params.more.list]]
            icon = "fa-keyboard-o"
            title = "Bonus: CLI client to Exabgp"
            description = "Erco provides a CLI client to interact with Exabgp"
            link = "/doc/cli.html"

    [params.install]
        headline = "Install Erco and control your Exabgp!"

        [params.install.button]
            text = "Installation instructions"
            link = "/doc/installation.html"

    [params.contribute]
        headline = "Contribute!"
        description = "You want to help, report a bug or ask for a feature?"
        bugs = "Report a bug or ask for a feature"
        bugsLink = "https://git.framasoft.org/luc/erco/issues"
        i18n = "Help to translate Erco"
        i18nLink = "https://www.transifex.com/projects/p/erco/resource/enpo-13/"
        source = "Get the source code"
        sourceLink = "https://git.framasoft.org/luc/erco"

    [params.author]
        name = "Luc Didry"
        avatar = "img/avatar.png"
        twitter = "framasky"
        diaspora = "https://framasphere.org/people/b13eb6b0beac0131e7e32a0000053625"
        site = "https://fiat-tux.fr"
        bio = "SysAdmin, Perl dev, geek.\nIn love with [Mojolicious](https://mojolicio.us).<br>See other developments at <https://git.framasoft.org/luc>"
        site_source = "https://git.framasoft.org/luc/erco-site"
